"""Tests for point sampling."""

from __future__ import annotations

import pytest
import xarray as xr

from snowsar.exceptions import AlgorithmError
from snowsar.output.point_query import Point, query_points


class TestQueryPoints:
    def test_nearest_returns_one_row_per_point_per_time(
        self, result_dataset_lonlat: xr.Dataset
    ) -> None:
        points = [
            Point(lon=-120.4, lat=37.6, id="a"),
            Point(lon=-120.2, lat=37.8, id="b"),
        ]
        df = query_points(result_dataset_lonlat, points)
        nt = result_dataset_lonlat.sizes["time"]
        assert len(df) == 2 * nt
        assert set(df["point_id"].unique()) == {"a", "b"}

    def test_empty_points_raises(self, result_dataset_lonlat: xr.Dataset) -> None:
        with pytest.raises(AlgorithmError, match="empty"):
            query_points(result_dataset_lonlat, [])

    def test_point_inside_grid_returns_non_nan_valid_pixel(
        self, result_dataset_lonlat: xr.Dataset
    ) -> None:
        # Center point should hit a valid pixel in most timesteps
        center_lon = float(result_dataset_lonlat["x"].values.mean())
        center_lat = float(result_dataset_lonlat["y"].values.mean())
        df = query_points(result_dataset_lonlat, [Point(lon=center_lon, lat=center_lat)])
        # At least one timestep must produce a numeric (non-null) snow_depth
        assert df["snow_depth"].notna().any()

    def test_autogenerated_ids_when_none(self, result_dataset_lonlat: xr.Dataset) -> None:
        df = query_points(
            result_dataset_lonlat,
            [Point(lon=-120.3, lat=37.7), Point(lon=-120.25, lat=37.75)],
        )
        assert set(df["point_id"].unique()) == {"p0", "p1"}

    def test_reprojects_when_src_crs_differs(self, synthetic_result_dataset: xr.Dataset) -> None:
        # Dataset is EPSG:32611 (UTM, meters). Supply a lon/lat point and let
        # query_points reproject to the Dataset's CRS.
        # Pick a lon/lat close to southern California; exact hit doesn't matter
        # — we only assert the call succeeds and returns rows.
        df = query_points(
            synthetic_result_dataset,
            [Point(lon=-118.0, lat=37.0)],
            src_crs="EPSG:4326",
        )
        assert len(df) == synthetic_result_dataset.sizes["time"]

    def test_missing_variables_are_skipped(self, result_dataset_lonlat: xr.Dataset) -> None:
        # Ask for a variable that doesn't exist plus one that does
        df = query_points(
            result_dataset_lonlat,
            [Point(lon=-120.3, lat=37.7)],
            variables=("snow_depth", "does_not_exist"),
        )
        assert "snow_depth" in df.columns
        assert "does_not_exist" not in df.columns

    def test_all_missing_variables_raises(self, result_dataset_lonlat: xr.Dataset) -> None:
        with pytest.raises(AlgorithmError, match="none of the requested variables"):
            query_points(
                result_dataset_lonlat,
                [Point(lon=-120.3, lat=37.7)],
                variables=("not_a_var",),
            )

    def test_integer_variable_uses_nearest_even_when_linear_requested(
        self, result_dataset_lonlat: xr.Dataset
    ) -> None:
        # quality_flag is uint8 — linear interp would produce non-integer
        # values, so the sampler must fall back to nearest.
        df = query_points(
            result_dataset_lonlat,
            [Point(lon=-120.25, lat=37.75)],
            method="linear",
        )
        # Integer values preserved — compare against the underlying dtype's set
        unique_vals = set(df["quality_flag"].dropna().astype(int).unique())
        # Integer flag values, no fractional interpolation
        assert all(v in range(0, 256) for v in unique_vals)
